[package]
name = "guess_the_number" # the name of the package
version = "0.1.0" # the current version, obeying semver
authors = ["ArhanCodes <arhan@peakseucation.com>"]

[dependencies]
rand = "0.8.4"
